# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'SwiftWebService' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWebService

	pod 'Alamofire', '~> 3.4'
	pod 'SwiftyJSON', '~> 2.3'

end
